apiVersion: v1
kind: Service
metadata:
  name: api-predictionsimilarite-service      
  namespace: test-technique-mlops
spec:
  type: LoadBalancer               
  selector:
    component: api-predictionsimilarite          #label de mes pods api
  ports:
    - protocol: TCP
      port: 80                      
      targetPort: 8000             
