_wandb:
    value:
        cli_version: 0.25.1
        e:
            nlg8mjchviwc5t6slhljjvh9k736e10o:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: src/modelisation.py
                codePathLocal: src/modelisation.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "200737861632"
                email: didymedide0808@gmail.com
                executable: /Users/dide/test_technique_mlops/mon_env/bin/python3.11
                git:
                    commit: ae569de9243aa44f505301035fcbaba8368cee8b
                host: MacBook-Air-de-DIDE.local
                memory:
                    total: "17179869184"
                os: macOS-15.7.4-arm64-arm-64bit
                program: /Users/dide/test_technique_mlops/src/modelisation.py
                python: CPython 3.11.15
                root: /Users/dide/test_technique_mlops
                startedAt: "2026-04-11T22:11:57.184322Z"
                writerId: nlg8mjchviwc5t6slhljjvh9k736e10o
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.11.15
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
colonnes_dataset:
    value:
        - sentence_1
        - sentence_2
        - similarity_score
        - prediction_score_similarite
dataset_size:
    value: all
max_features:
    value: 5000
model_type:
    value: TF-IDF + Cosine
nombredelignes_dataset:
    value: 34560
